# Generated by Django 3.1.14 on 2022-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_pokemonentity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='description',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='Pokemon Go!', verbose_name='описание'),
            preserve_default=False,
        ),
    ]
